name: CI

on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run k6's golangci-lint CI
        uses: grafana/k6/.github/actions/lint@master

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Check build
        run: |
          go version
          pwd && ls -l

          go install go.k6.io/xk6/cmd/xk6@master
          MODULE_NAME=`go list -m`

          GOPRIVATE="go.k6.io/k6" xk6 build \
            --output ./k6ext \
            --with $MODULE_NAME="."
          ./k6ext version

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Run tests
        run: |
          go version
          pwd && ls -l

          go test -v ./...