name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@e4a5a88f7cc2665f36bf87bd5a592901469138c1  # v1.2.3
    permissions:
      issues: write